config/routes.rb
PFLiveEvents::Application.routes.draw do
  mount Apic::Engine => "/apic"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  get '/health_check' => 'health_check#check'
  get "/test_exception" => "application#test_exception"

  if Rails.env != 'production-admin'

    if Rails.env == 'production'
      # api hardening -- next line to be expanded to only diner dash capable devices
      #constraints(lambda { |req| req.env["HTTP_USER_AGENT"] =~ /iPhone/ }) do

        namespace :api do

          get "/connect" => "connect#index", :as => :connect
          get "/test" => "test#index", :as => :test
          get "/update_score" => "update_score#index", :as => :update_score
          get "/view_leaderboard" => "view_leaderboard#index", :as => :view_leaderboard
          get "/available_awards" => "available_awards#index", :as => :available_awards
          get "/request_award" => "request_award#index", :as => :request_award
          get "/request_token" => "request_token#index", :as => :request_token
      

          #curl -X POST -d "" localhost:3000/api/register_for_pfid      
          post "/register_for_pfid" => "pfid#register_for_pfid"
          #curl -X GET localhost:3000/api/get_pfid
          get "/get_pfid" => "pfid#get_pfid"
        end
      
  end
  if Rails.env != 'production'

      namespace :api do

        get "/connect" => "connect#index", :as => :connect
        get "/test" => "test#index", :as => :test
        get "/update_score" => "update_score#index", :as => :update_score
        get "/view_leaderboard" => "view_leaderboard#index", :as => :view_leaderboard
        get "/available_awards" => "available_awards#index", :as => :available_awards
        get "/request_award" => "request_award#index", :as => :request_award
        get "/request_token" => "request_token#index", :as => :request_token
    

        #curl -X POST -d "" localhost:3000/api/register_for_pfid      
        post "/register_for_pfid" => "pfid#register_for_pfid"
        #curl -X GET localhost:3000/api/get_pfid
        get "/get_pfid" => "pfid#get_pfid"
      end
  end
    
end

  if Rails.env != 'production-api'
    root :controller => :events, :action => :index

    resources :apps, :except => :show
    resources :events, :except => :show
    resources :scores, :except => :show

    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'sign_in', to: redirect('/users/auth/google_oauth2/'), :as => :new_user_session
    end
  end

end

app/models/score.rb
class Score < ActiveRecord::Base
  include GuidPrimaryKey
  belongs_to :event, class_name: "Event", foreign_key: "event_id"

  scope :join_cheaters, lambda { select("scores.*, cheaters.id AS cheater_id, cheaters.notes AS cheater_notes").joins("LEFT OUTER JOIN cheaters ON scores.player_id = cheaters.player_id") }
  scope :no_cheaters, lambda { joins("LEFT OUTER JOIN cheaters ON scores.player_id = cheaters.player_id").where("cheaters.player_id IS NULL") }
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_score, :only => [:show, :edit, :update, :destroy]

  SORT_ORDER = {
    'player_asc' => 'Player (a-z)',
    'player_desc' => 'Player (z-a)',
    'value_asc' => 'Value (lowest)',
    'value_desc' => 'Value (highest)',
    'update_asc' => 'Update (oldest)',
    'update_desc' => 'Update (newest)'
  }

  SORT_ORDER_SQL = {
    'player_asc' => 'player_id ASC',
    'player_desc' => 'player_id DESC',
    'value_asc' => 'value ASC',
    'value_desc' => 'value DESC',
    'update_asc' => 'updated_at ASC',
    'update_desc' => 'updated_at DESC',
  }

  PAGINATION_OPTIONS = {
    '15' => '15',
    '20' => '20',
    '50' => '50',
    '0' => 'All'
  }

  def index
    params[:page] = '1' if params[:search].present? || params[:per_page].present?
    params[:event_id] = '' if params[:app_id].present?
    params[:name] = '' if params[:app_id].present? || params[:event_id].present?
    merge_cookie_params

    filters = ""
    if params[:event_id].present?
      filters += ") AND (" if !filters.empty?
      filters += "`scores`.`event_id` = '#{params[:event_id]}'"
      @event = Event.find_by_id(params[:event_id])
    end
    if params[:name].present?
      filters += ") AND (" if !filters.empty?
      filters += "`scores`.`name` = '#{params[:name]}'"
    end
    if params[:player].present?
      filters += ") AND (" if !filters.empty?
      filters += "`events`.`player_id` LIKE '%#{params[:player]}%'"
    end

    # Apply defaults
    params[:sort_by] = 'value_desc' if !params[:sort_by].present?
    params[:per_page] = '15' if !params[:per_page].present?
    params[:page] = '1' if !params[:page].present?

    if params[:app_id].present?
      @events = Event.where("`events`.`app_id` = '#{params[:app_id]}'")
      if params[:event_id].present?
        @score_names = Score.where("`scores`.`event_id` = '#{params[:event_id]}'").uniq.pluck(:name)
        if params[:name].present?
          if params[:per_page] != '0'
            @scores = Score.where(filters).paginate(:page => params[:page], :per_page => params[:per_page]).reorder(SORT_ORDER_SQL[params[:sort_by]]).join_cheaters
          else
            @scores = Score.where(filters).reorder(SORT_ORDER_SQL[params[:sort_by]]).join_cheaters
          end
        end
      end
      @app = App.find_by_id(params[:app_id])
    end

    save_cookie_params
  end

  def edit
  end

  def update
    if (defined? params[:score][:cheater_notes]) && params[:score][:cheater_notes] != @score.cheater_notes
      logger.info params[:score][:cheater_notes]
      logger.info @score.cheater_notes
      cheater = Cheater.where({:player_id => @score.player_id}).first
      if params[:score][:cheater_notes].present?
        if cheater.nil?
          flash[:error] = "Banned player as a cheater"
          cheater = Cheater.create(player_id: @score.player_id, notes: params[:score][:cheater_notes])
        else
          flash[:error] = "Updated cheater description"
          cheater.notes = params[:score][:cheater_notes]
          cheater.save
        end
      else
        flash[:error] = "Un-banned player"
        if !cheater.nil?
          cheater.delete
        end
      end
    end
    if params[:score][:value].to_i != @score.value
      if @score.update_attributes(score_params)
        flash[:notice] = "Successfully updated score"
      else
        flash.now[:error] = "Error updating score"
        render :action => :edit
        return
      end
    end
    redirect_to scores_path
  end

  private

    def merge_cookie_params
      params[:app_id] = cookies[:score_app_id] if params[:app_id].nil? && cookies[:score_app_id].present?
      params[:event_id] = cookies[:score_event_id] if params[:event_id].nil? && cookies[:score_event_id].present?
      params[:name] = cookies[:score_name] if params[:name].nil? && cookies[:score_name].present?
      params[:player_id] = cookies[:score_player_id] if params[:player_id].nil? && cookies[:score_player_id].present?
      params[:sort_by] = cookies[:score_sort_by] if params[:sort_by].nil? && cookies[:score_sort_by].present?
      params[:page] = cookies[:score_page] if params[:page].nil? && cookies[:score_page].present?
      params[:per_page] = cookies[:score_per_page] if params[:per_page].nil? && cookies[:score_per_page].present?
    end

    def save_cookie_params
      cookies[:score_app_id] = params[:app_id] if !params[:app_id].nil?
      cookies[:score_event_id] = params[:event_id] if !params[:event_id].nil?
      cookies[:score_name] = params[:name] if !params[:name].nil?
      cookies[:score_player_id] = params[:player_id] if !params[:player_id].nil?
      cookies[:score_sort_by] = params[:sort_by] if !params[:sort_by].nil?
      cookies[:score_page] = params[:page] if !params[:page].nil?
      cookies[:score_per_page] = params[:per_page] if !params[:per_page].nil?
    end

    def score_params
      params.require(:score).permit(:value)
    end

    def find_score
      @score = Score.where(:id => params[:id]).join_cheaters.first
    end

end

app/views/scores/_form.html.haml
.row
  .small-8.small-offset-2.columns
    = form_for @score do |f|
      - if @score.errors.any?
        #error_explanation
          %h2= "#{pluralize(@score.errors.count, "error")} prohibited this score from being saved:"
          %ul
            - @score.errors.full_messages.each do |msg|
              %li= msg

      %fieldset
        .row
          .small-10.small-offset-1.columns
            = f.label :event, "Event"
            &nbsp; &nbsp; #{@score.event.app.name} - #{@score.event.name}
        .row
          .small-10.small-offset-1.columns
            = f.label :player, "Player"
            &nbsp; &nbsp; #{@score.player_id}
        .row
          .small-10.small-offset-1.columns
            = f.label :score_name, "Score Name"
            &nbsp; &nbsp; #{@score.name}

      %fieldset
        .row
          .small-10.small-offset-1.columns
            = f.label :value, "Value (changing this value may not update the client)"
            = f.text_field :value
        .row
          .small-10.small-offset-1.columns
            = f.label :milestone, "Highest Milestone Attained"
            = f.text_field :milestone
        .row
          .small-10.small-offset-1.columns
            = f.label :reward, "Associated Reward with Highest Milestone"
            = f.text_field :reward
        .row
          .small-10.small-offset-1.columns
            = f.label :cheater_notes, "Cheater Notes (if provided, player will be banned from all events)"
            = f.text_field :cheater_notes
        .row
          .small-6.small-offset-3.columns
            = f.submit 'Save', :class => 'button'
            = link_to 'Cancel', scores_path, :class => 'button alert'

app/views/scores/edit.html.haml
%h2 Edit Score
= render 'form'

app/views/scores/index.html.haml
- content_for :page_style do
  \.vcenter {vertical-align:middle !important;}
  \.hcenter {text-align:center !important;}
  \.filters {display: inline-block; width: 65%;}
  \.sort_options {display: inline-block; width: 32%; text-align:right;}

.row
  .small-8.columns
    %h2 Scores
.row
  .filters
    %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'apps'}}
      = @app.present? ? "#{@app.name}" : "Select an App"
    %ul#apps.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
      - App.all.each do |app|
        %li= link_to app.name, scores_path(:app_id => app.id) if params[:app_id] != app.id
    - if !@events.nil? && !@events.empty?
      %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'events'}}
        = @event.present? ? "#{@event.name}" : "Select an Event"
      %ul#events.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
        - @events.each do |event|
          %li= link_to event.name, scores_path(:event_id => event.id) if params[:event_id] != event.id
    - if !@score_names.nil? && !@score_names.empty?
      %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'names'}}
        = params[:name].present? ? params[:name] : "Select a Score Type"
      %ul#names.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
        - @score_names.each do |score_name|
          %li= link_to score_name, scores_path(:name => score_name) if params[:name] != score_name
    - if !@scores.nil?
      Player:
      %input{:type=>"text", :value => params[:player_id], :onchange => "window.location.href=\"#{scores_path()}?player_id=\"+this.value;", :style => "display: inline-block; margin-bottom: 0px; width: 100px;"}
  .sort_options
    Sort:
    %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'sort_by'}}
      = params[:sort_by] ? "#{ScoresController::SORT_ORDER[params[:sort_by]] || 'Value (highest)'}" : "Value (highest)"
    %ul#sort_by.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
      - ScoresController::SORT_ORDER.each do |order|
        %li= link_to order.second, scores_path(:sort_by => order.first) if params[:sort_by] != order.first
    Per Page:
    %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'per_page'}}
      = params[:per_page] != '0' ? "#{params[:per_page] || '15'}" : 'All'
    %ul#per_page.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
      - ScoresController::PAGINATION_OPTIONS.each do |per_page|
        %li= link_to per_page.second, scores_path(:per_page => per_page.first) if params[:per_page] != per_page.first

%table.scores-table{:style => 'width: 100%;'}
  %thead
    %tr
      %th Player
      %th Value
      %th Milestone
      %th Reward
      %th Last Update
      %th
  %tbody
    - if !@scores.nil? && !@scores.empty?
      - @scores.each do |score|
        %tr
          %td.vcenter{:style => score.cheater_id.present? ? "color:red;" : ""}
            = score.player_id
          %td.vcenter{:style => score.cheater_id.present? ? "color:red;" : ""}
            = score.value
          %td.vcenter{:style => score.cheater_id.present? ? "color:red;" : ""}
            = score.milestone
          %td.vcenter{:style => score.cheater_id.present? ? "color:red;" : ""}
            = score.reward
          %td.vcenter{:style => score.cheater_id.present? ? "color:red;" : ""}
            = score.updated_at.in_time_zone('America/Los_Angeles').to_formatted_s(:db)
          %td.vcenter
            = link_to edit_score_path(score) do
              %i.fi-pencil.button.tiny.success{:style => "margin: 0px;padding: 0.3rem 0.5rem;"}

- if !@events.nil? && @events.empty?
  .centered
    No events yet

- if !@score_names.nil? && @score_names.empty?
  .centered
    No scores yet

.pagination-centered
  = foundation_paginate @scores if !@scores.nil? && params[:per_page] != '0'