config/routes.rb
PFLiveEvents::Application.routes.draw do
  mount Apic::Engine => "/apic"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  get '/health_check' => 'health_check#check'
  get "/test_exception" => "application#test_exception"

  if Rails.env != 'production-admin'

    if Rails.env == 'production'
      # api hardening -- next line to be expanded to only diner dash capable devices
      #constraints(lambda { |req| req.env["HTTP_USER_AGENT"] =~ /iPhone/ }) do

        namespace :api do

          get "/connect" => "connect#index", :as => :connect
          get "/test" => "test#index", :as => :test
          get "/update_score" => "update_score#index", :as => :update_score
          get "/view_leaderboard" => "view_leaderboard#index", :as => :view_leaderboard
          get "/available_awards" => "available_awards#index", :as => :available_awards
          get "/request_award" => "request_award#index", :as => :request_award
          get "/request_token" => "request_token#index", :as => :request_token
      

          #curl -X POST -d "" localhost:3000/api/register_for_pfid      
          post "/register_for_pfid" => "pfid#register_for_pfid"
          #curl -X GET localhost:3000/api/get_pfid
          get "/get_pfid" => "pfid#get_pfid"
        end
      
  end
  if Rails.env != 'production'

      namespace :api do

        get "/connect" => "connect#index", :as => :connect
        get "/test" => "test#index", :as => :test
        get "/update_score" => "update_score#index", :as => :update_score
        get "/view_leaderboard" => "view_leaderboard#index", :as => :view_leaderboard
        get "/available_awards" => "available_awards#index", :as => :available_awards
        get "/request_award" => "request_award#index", :as => :request_award
        get "/request_token" => "request_token#index", :as => :request_token
    

        #curl -X POST -d "" localhost:3000/api/register_for_pfid      
        post "/register_for_pfid" => "pfid#register_for_pfid"
        #curl -X GET localhost:3000/api/get_pfid
        get "/get_pfid" => "pfid#get_pfid"
      end
  end
    
end

  if Rails.env != 'production-api'
    root :controller => :events, :action => :index

    resources :apps, :except => :show
    resources :events, :except => :show
    resources :scores, :except => :show

    devise_scope :user do
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
      get 'sign_in', to: redirect('/users/auth/google_oauth2/'), :as => :new_user_session
    end
  end

end

app/views/apps/_form.html.haml
.row
  .small-8.small-offset-2.columns
    = form_for @app do |f|
      - if @app.errors.any?
        #error_explanation
          %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
          %ul
            - @app.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        .row
          .small-10.small-offset-1.columns
            = f.label :name
            = f.text_field :name
        .row
          .small-10.small-offset-1.columns
            = f.label :id, "Game ID"
            = f.text_field :id, :disabled => @app.id?
        .row
          .small-10.small-offset-1.columns
            = f.label :id, "Secret Key"
            = f.text_field :secret_key, :disabled => @app.secret_key?
        .row
          .small-6.small-offset-3.columns
            = f.submit 'Save', :class => 'button'
            = link_to 'Cancel', apps_path, :class => 'button alert'

app/views/apps/edit.html.haml
%h2 Edit App
= render 'form'

app/views/apps/index.html.haml
- content_for :page_style do
  \.vcenter {vertical-align:middle !important;}
  \.hcenter {text-align:center !important;}
  \.filters {display: inline-block; width: 65%;}
  \.sort_options {display: inline-block; width: 32%; text-align:right;}
  \#order {display: inline;}
  \#new {padding: 15px;}

.row
  .small-8.columns
    %h2 Apps
  .small-4.columns
    = link_to new_app_path, :class => "button tiny right", :style => "margin: 10px;" do
      %i.fi-plus
.row
  .filters
    Search:
    %input{:type=>"text", :value => params[:search], :onchange => "window.location.href=\"#{apps_path()}?search=\"+this.value;", :style => "display: inline-block; margin-bottom: 0px; width: 200px;"}
  .sort_options
    %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'sort_by'}}
      = params[:sort_by] ? "#{AppsController::SORT_ORDER[params[:sort_by]] || 'Name (a-z)'}" : "Name (a-z)"
    %ul#sort_by.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
      - AppsController::SORT_ORDER.each do |order|
        %li= link_to order.second, apps_path(:sort_by => order.first) if params[:sort_by] != order.first
    Per Page:
    %a.button.tiny.dropdown{:href => '#', :data => {:dropdown => 'per_page'}}
      = params[:per_page] != '0' ? "#{params[:per_page] || '15'}" : 'All'
    %ul#per_page.f-dropdown{:data => {'dropdown-content' => true}, :style => 'max-width: 300px;'}
      - AppsController::PAGINATION_OPTIONS.each do |per_page|
        %li= link_to per_page.second, apps_path(:per_page => per_page.first) if params[:per_page] != per_page.first

%table.apps-table{:style => 'width: 100%;'}
  %thead
    %tr
      %th Name
      %th ID
      %th Secret Key
      %th
  %tbody
    - if !@apps.empty?
      - @apps.each do |app|
        %tr
          %td.vcenter
            = app.name
          %td.vcenter
            = app.id
          %td.vcenter
            = app.secret_key
          %td.vcenter
            %ul.button-group.right.controls
              %li
                = link_to edit_app_path(app) do
                  %i.fi-pencil.button.tiny.success{:style => "margin: 0px;padding: 0.3rem 0.5rem;"}
              %li
                = link_to app, :method => :delete, :data => { :confirm => "Delete #{app.name}?" } do
                  %i.fi-x.button.tiny.alert{:style => "margin: 0px;padding: 0.3rem 0.5rem;"}

.pagination-centered
  = foundation_paginate @apps if params[:per_page] != '0'

app/views/apps/new.html.haml
%h2 New App

= render 'form'

app/views/apps/show.html.haml
%h3= @app.name